"""remove pk on rating

Revision ID: 003c6e67b184
Revises: 21b44601b63e
Create Date: 2023-02-06 18:07:36.744573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003c6e67b184'
down_revision = '21b44601b63e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
