"""setting serial on pk

Revision ID: 21b44601b63e
Revises: ecab1836d238
Create Date: 2023-02-06 18:04:19.386298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b44601b63e'
down_revision = 'ecab1836d238'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
