"""rating como float refinado2

Revision ID: 22e1487d51ed
Revises: 92c6939a34b3
Create Date: 2023-02-07 15:29:53.961817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e1487d51ed'
down_revision = '92c6939a34b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
