"""Introduzindo Owner

Revision ID: 89a45f42bdc4
Revises: eb1f809fa61a
Create Date: 2023-02-06 13:58:11.265617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a45f42bdc4'
down_revision = 'eb1f809fa61a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'owner_id')
    # ### end Alembic commands ###
