"""rating como float refinado

Revision ID: 92c6939a34b3
Revises: 944fcdc4e5fa
Create Date: 2023-02-07 15:27:58.610334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c6939a34b3'
down_revision = '944fcdc4e5fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
