"""rating como float

Revision ID: 944fcdc4e5fa
Revises: 003c6e67b184
Create Date: 2023-02-07 15:15:20.148287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944fcdc4e5fa'
down_revision = '003c6e67b184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
